package hibernate;
// Generated Aug 13, 2016 2:10:11 PM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cartId;
     private ProductSize productSize;
     private ProductByColor productByColor;
     private User user;
     private Boolean isCart;
     private Boolean isWishList;
     private Boolean isOrder;
     private String trxId;

    public Cart() {
    }

	
    public Cart(ProductSize productSize, ProductByColor productByColor, User user) {
        this.productSize = productSize;
        this.productByColor = productByColor;
        this.user = user;
    }
    public Cart(ProductSize productSize, ProductByColor productByColor, User user, Boolean isCart, Boolean isWishList, Boolean isOrder, String trxId) {
       this.productSize = productSize;
       this.productByColor = productByColor;
       this.user = user;
       this.isCart = isCart;
       this.isWishList = isWishList;
       this.isOrder = isOrder;
       this.trxId = trxId;
    }
   
    public Integer getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
    public ProductSize getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(ProductSize productSize) {
        this.productSize = productSize;
    }
    public ProductByColor getProductByColor() {
        return this.productByColor;
    }
    
    public void setProductByColor(ProductByColor productByColor) {
        this.productByColor = productByColor;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Boolean getIsCart() {
        return this.isCart;
    }
    
    public void setIsCart(Boolean isCart) {
        this.isCart = isCart;
    }
    public Boolean getIsWishList() {
        return this.isWishList;
    }
    
    public void setIsWishList(Boolean isWishList) {
        this.isWishList = isWishList;
    }
    public Boolean getIsOrder() {
        return this.isOrder;
    }
    
    public void setIsOrder(Boolean isOrder) {
        this.isOrder = isOrder;
    }
    public String getTrxId() {
        return this.trxId;
    }
    
    public void setTrxId(String trxId) {
        this.trxId = trxId;
    }




}


