package hibernate;
// Generated Aug 20, 2016 2:15:55 PM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer cartId;
     private ProductSize productSize;
     private ProductByColor productByColor;
     private User user;
     private Boolean isCart;
     private Boolean isWishList;
     private Boolean isOrder;
     private Boolean isConfirm;
     private Boolean isDispatched;
     private Boolean isReceivedByCustomer;
     private int quantity;
     private String trxId;

    public Cart() {
    }

	
    public Cart(ProductSize productSize, ProductByColor productByColor, User user, int quantity) {
        this.productSize = productSize;
        this.productByColor = productByColor;
        this.user = user;
        this.quantity = quantity;
    }
    public Cart(ProductSize productSize, ProductByColor productByColor, User user, Boolean isCart, Boolean isWishList, Boolean isOrder, Boolean isConfirm, Boolean isDispatched, Boolean isReceivedByCustomer, int quantity, String trxId) {
       this.productSize = productSize;
       this.productByColor = productByColor;
       this.user = user;
       this.isCart = isCart;
       this.isWishList = isWishList;
       this.isOrder = isOrder;
       this.isConfirm = isConfirm;
       this.isDispatched = isDispatched;
       this.isReceivedByCustomer = isReceivedByCustomer;
       this.quantity = quantity;
       this.trxId = trxId;
    }
   
    public Integer getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
    public ProductSize getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(ProductSize productSize) {
        this.productSize = productSize;
    }
    public ProductByColor getProductByColor() {
        return this.productByColor;
    }
    
    public void setProductByColor(ProductByColor productByColor) {
        this.productByColor = productByColor;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Boolean getIsCart() {
        return this.isCart;
    }
    
    public void setIsCart(Boolean isCart) {
        this.isCart = isCart;
    }
    public Boolean getIsWishList() {
        return this.isWishList;
    }
    
    public void setIsWishList(Boolean isWishList) {
        this.isWishList = isWishList;
    }
    public Boolean getIsOrder() {
        return this.isOrder;
    }
    
    public void setIsOrder(Boolean isOrder) {
        this.isOrder = isOrder;
    }
    public Boolean getIsConfirm() {
        return this.isConfirm;
    }
    
    public void setIsConfirm(Boolean isConfirm) {
        this.isConfirm = isConfirm;
    }
    public Boolean getIsDispatched() {
        return this.isDispatched;
    }
    
    public void setIsDispatched(Boolean isDispatched) {
        this.isDispatched = isDispatched;
    }
    public Boolean getIsReceivedByCustomer() {
        return this.isReceivedByCustomer;
    }
    
    public void setIsReceivedByCustomer(Boolean isReceivedByCustomer) {
        this.isReceivedByCustomer = isReceivedByCustomer;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getTrxId() {
        return this.trxId;
    }
    
    public void setTrxId(String trxId) {
        this.trxId = trxId;
    }




}


