package hibernate;
// Generated Aug 13, 2016 2:10:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FirstSubcategory generated by hbm2java
 */
public class FirstSubcategory  implements java.io.Serializable {


     private Integer firstSubcategoryId;
     private MainCategory mainCategory;
     private String name;
     private Set<SecondSubcategory> secondSubcategories = new HashSet<SecondSubcategory>(0);
     private Set<ProductDetail> productDetails = new HashSet<ProductDetail>(0);

    public FirstSubcategory() {
    }

	
    public FirstSubcategory(MainCategory mainCategory, String name) {
        this.mainCategory = mainCategory;
        this.name = name;
    }
    public FirstSubcategory(MainCategory mainCategory, String name, Set<SecondSubcategory> secondSubcategories, Set<ProductDetail> productDetails) {
       this.mainCategory = mainCategory;
       this.name = name;
       this.secondSubcategories = secondSubcategories;
       this.productDetails = productDetails;
    }
   
    public Integer getFirstSubcategoryId() {
        return this.firstSubcategoryId;
    }
    
    public void setFirstSubcategoryId(Integer firstSubcategoryId) {
        this.firstSubcategoryId = firstSubcategoryId;
    }
    public MainCategory getMainCategory() {
        return this.mainCategory;
    }
    
    public void setMainCategory(MainCategory mainCategory) {
        this.mainCategory = mainCategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<SecondSubcategory> getSecondSubcategories() {
        return this.secondSubcategories;
    }
    
    public void setSecondSubcategories(Set<SecondSubcategory> secondSubcategories) {
        this.secondSubcategories = secondSubcategories;
    }
    public Set<ProductDetail> getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set<ProductDetail> productDetails) {
        this.productDetails = productDetails;
    }




}


