package hibernate;
// Generated Aug 13, 2016 4:59:35 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductDetail generated by hbm2java
 */
public class ProductDetail implements java.io.Serializable {

    private Integer productDetailId;
    private FirstSubcategory firstSubcategory;
    private MainCategory mainCategory;
    private SecondSubcategory secondSubcategory;
    private String searchTag;
    private String productDetail;
    private String materialDetail;
    private String care;
    private int sellingPrice;
    private int displayPrice;
    private Set<ProductByColor> productByColors = new HashSet<ProductByColor>(0);
    private Set<ProductSize> productSizes = new HashSet<ProductSize>(0);

    public ProductDetail() {
    }

    public ProductDetail(FirstSubcategory firstSubcategory, MainCategory mainCategory, SecondSubcategory secondSubcategory, String searchTag, String productDetail, String materialDetail, String care, int sellingPrice, int displayPrice) {
        this.firstSubcategory = firstSubcategory;
        this.mainCategory = mainCategory;
        this.secondSubcategory = secondSubcategory;
        this.searchTag = searchTag;
        this.productDetail = productDetail;
        this.materialDetail = materialDetail;
        this.care = care;
        this.sellingPrice = sellingPrice;
        this.displayPrice = displayPrice;
    }

    public ProductDetail(FirstSubcategory firstSubcategory, MainCategory mainCategory, SecondSubcategory secondSubcategory, String searchTag, String productDetail, String materialDetail, String care, int sellingPrice, int displayPrice, Set<ProductByColor> productByColors, Set<ProductSize> productSizes) {
        this.firstSubcategory = firstSubcategory;
        this.mainCategory = mainCategory;
        this.secondSubcategory = secondSubcategory;
        this.searchTag = searchTag;
        this.productDetail = productDetail;
        this.materialDetail = materialDetail;
        this.care = care;
        this.sellingPrice = sellingPrice;
        this.displayPrice = displayPrice;
        this.productByColors = productByColors;
        this.productSizes = productSizes;
    }

    public Integer getProductDetailId() {
        return this.productDetailId;
    }

    public void setProductDetailId(Integer productDetailId) {
        this.productDetailId = productDetailId;
    }

    public FirstSubcategory getFirstSubcategory() {
        return this.firstSubcategory;
    }

    public void setFirstSubcategory(FirstSubcategory firstSubcategory) {
        this.firstSubcategory = firstSubcategory;
    }

    public MainCategory getMainCategory() {
        return this.mainCategory;
    }

    public void setMainCategory(MainCategory mainCategory) {
        this.mainCategory = mainCategory;
    }

    public SecondSubcategory getSecondSubcategory() {
        return this.secondSubcategory;
    }

    public void setSecondSubcategory(SecondSubcategory secondSubcategory) {
        this.secondSubcategory = secondSubcategory;
    }

    public String getSearchTag() {
        return this.searchTag;
    }

    public void setSearchTag(String searchTag) {
        this.searchTag = searchTag;
    }

    public String getProductDetail() {
        return this.productDetail;
    }

    public void setProductDetail(String productDetail) {
        this.productDetail = productDetail;
    }

    public String getMaterialDetail() {
        return this.materialDetail;
    }

    public void setMaterialDetail(String materialDetail) {
        this.materialDetail = materialDetail;
    }

    public String getCare() {
        return this.care;
    }

    public void setCare(String care) {
        this.care = care;
    }

    public int getSellingPrice() {
        return this.sellingPrice;
    }

    public void setSellingPrice(int sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    public int getDisplayPrice() {
        return this.displayPrice;
    }

    public void setDisplayPrice(int displayPrice) {
        this.displayPrice = displayPrice;
    }

    public Set<ProductByColor> getProductByColors() {
        return this.productByColors;
    }

    public void setProductByColors(Set<ProductByColor> productByColors) {
        this.productByColors = productByColors;
    }

    public Set<ProductSize> getProductSizes() {
        return this.productSizes;
    }

    public void setProductSizes(Set<ProductSize> productSizes) {
        this.productSizes = productSizes;
    }

}
