package hibernate;
// Generated Aug 20, 2016 2:15:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductSize generated by hbm2java
 */
public class ProductSize  implements java.io.Serializable {


     private Integer productSizeId;
     private ProductDetail productDetail;
     private String sizeType;
     private Set<SizeStockByColor> sizeStockByColors = new HashSet<SizeStockByColor>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);

    public ProductSize() {
    }

	
    public ProductSize(ProductDetail productDetail, String sizeType) {
        this.productDetail = productDetail;
        this.sizeType = sizeType;
    }
    public ProductSize(ProductDetail productDetail, String sizeType, Set<SizeStockByColor> sizeStockByColors, Set<Cart> carts) {
       this.productDetail = productDetail;
       this.sizeType = sizeType;
       this.sizeStockByColors = sizeStockByColors;
       this.carts = carts;
    }
   
    public Integer getProductSizeId() {
        return this.productSizeId;
    }
    
    public void setProductSizeId(Integer productSizeId) {
        this.productSizeId = productSizeId;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public String getSizeType() {
        return this.sizeType;
    }
    
    public void setSizeType(String sizeType) {
        this.sizeType = sizeType;
    }
    public Set<SizeStockByColor> getSizeStockByColors() {
        return this.sizeStockByColors;
    }
    
    public void setSizeStockByColors(Set<SizeStockByColor> sizeStockByColors) {
        this.sizeStockByColors = sizeStockByColors;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


