package hibernate;
// Generated Aug 13, 2016 2:10:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductByColor generated by hbm2java
 */
public class ProductByColor  implements java.io.Serializable {


     private Integer productByColorId;
     private ProductDetail productDetail;
     private String name;
     private String title;
     private String hex;
     private Set<ProductByColorImages> productByColorImageses = new HashSet<ProductByColorImages>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<SizeStockByColor> sizeStockByColors = new HashSet<SizeStockByColor>(0);

    public ProductByColor() {
    }

	
    public ProductByColor(ProductDetail productDetail, String name, String title, String hex) {
        this.productDetail = productDetail;
        this.name = name;
        this.title = title;
        this.hex = hex;
    }
    public ProductByColor(ProductDetail productDetail, String name, String title, String hex, Set<ProductByColorImages> productByColorImageses, Set<Cart> carts, Set<SizeStockByColor> sizeStockByColors) {
       this.productDetail = productDetail;
       this.name = name;
       this.title = title;
       this.hex = hex;
       this.productByColorImageses = productByColorImageses;
       this.carts = carts;
       this.sizeStockByColors = sizeStockByColors;
    }
   
    public Integer getProductByColorId() {
        return this.productByColorId;
    }
    
    public void setProductByColorId(Integer productByColorId) {
        this.productByColorId = productByColorId;
    }
    public ProductDetail getProductDetail() {
        return this.productDetail;
    }
    
    public void setProductDetail(ProductDetail productDetail) {
        this.productDetail = productDetail;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getHex() {
        return this.hex;
    }
    
    public void setHex(String hex) {
        this.hex = hex;
    }
    public Set<ProductByColorImages> getProductByColorImageses() {
        return this.productByColorImageses;
    }
    
    public void setProductByColorImageses(Set<ProductByColorImages> productByColorImageses) {
        this.productByColorImageses = productByColorImageses;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<SizeStockByColor> getSizeStockByColors() {
        return this.sizeStockByColors;
    }
    
    public void setSizeStockByColors(Set<SizeStockByColor> sizeStockByColors) {
        this.sizeStockByColors = sizeStockByColors;
    }




}


