package hibernate;
// Generated Aug 20, 2016 2:15:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SecondSubcategory generated by hbm2java
 */
public class SecondSubcategory  implements java.io.Serializable {


     private Integer secondSubcategoryId;
     private FirstSubcategory firstSubcategory;
     private String name;
     private Set<ProductDetail> productDetails = new HashSet<ProductDetail>(0);

    public SecondSubcategory() {
    }

	
    public SecondSubcategory(FirstSubcategory firstSubcategory, String name) {
        this.firstSubcategory = firstSubcategory;
        this.name = name;
    }
    public SecondSubcategory(FirstSubcategory firstSubcategory, String name, Set<ProductDetail> productDetails) {
       this.firstSubcategory = firstSubcategory;
       this.name = name;
       this.productDetails = productDetails;
    }
   
    public Integer getSecondSubcategoryId() {
        return this.secondSubcategoryId;
    }
    
    public void setSecondSubcategoryId(Integer secondSubcategoryId) {
        this.secondSubcategoryId = secondSubcategoryId;
    }
    public FirstSubcategory getFirstSubcategory() {
        return this.firstSubcategory;
    }
    
    public void setFirstSubcategory(FirstSubcategory firstSubcategory) {
        this.firstSubcategory = firstSubcategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<ProductDetail> getProductDetails() {
        return this.productDetails;
    }
    
    public void setProductDetails(Set<ProductDetail> productDetails) {
        this.productDetails = productDetails;
    }




}


