package hibernate;
// Generated Aug 13, 2016 2:10:11 PM by Hibernate Tools 4.3.1



/**
 * SizeStockByColor generated by hbm2java
 */
public class SizeStockByColor  implements java.io.Serializable {


     private Integer sizeStockByColorId;
     private ProductSize productSize;
     private ProductByColor productByColor;
     private int stock;

    public SizeStockByColor() {
    }

    public SizeStockByColor(ProductSize productSize, ProductByColor productByColor, int stock) {
       this.productSize = productSize;
       this.productByColor = productByColor;
       this.stock = stock;
    }
   
    public Integer getSizeStockByColorId() {
        return this.sizeStockByColorId;
    }
    
    public void setSizeStockByColorId(Integer sizeStockByColorId) {
        this.sizeStockByColorId = sizeStockByColorId;
    }
    public ProductSize getProductSize() {
        return this.productSize;
    }
    
    public void setProductSize(ProductSize productSize) {
        this.productSize = productSize;
    }
    public ProductByColor getProductByColor() {
        return this.productByColor;
    }
    
    public void setProductByColor(ProductByColor productByColor) {
        this.productByColor = productByColor;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }




}


